spring:
  application:
    name: servicescontrats
  datasource:
    url: jdbc:postgresql://localhost:5432/assurance_db
    username: postgres
    password: baac
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  mail:
    host: localhost
    port: 9025
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
entities:
  scan:
    packages:
      - org.example.serviceclients
      - org.example.servicecontrats
kafka:
  producer:
    group-id: notification-group
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
