spring:
  kafka:
  producer:
  bootstrap-servers: localhost:9092
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: servicesclients
  datasource:
    url: jdbc:postgresql://localhost:5432/assurance_db
    username: postgres
    password: baac
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
    feign: DEBUG
    org.example.servicecontrats.feignclients: DEBUG

mail:
  host: localhost  # Mail server host
  port: 9025 # Mail server port


